"""
KIS API 설계 문제 설명
"""
print("="*80)
print("문제 상황")
print("="*80)
print()
print("사용자: '내 USD 잔고만 보여줘'")
print()
print("하지만 KIS API는:")
print("  TTTS3007R (매매가능금액조회)")
print("  - 목적: '특정 종목을 매수 가능한 금액 조회'")
print("  - 필수 파라미터:")
print("    * ITEM_CD: 종목코드 (예: SOXL)")
print("    * OVRS_EXCG_CD: 거래소코드 (예: AMEX)")
print("    * OVRS_ORD_UNPR: 주문단가")
print()
print("즉, '순수 USD 잔고만 조회'하는 API가 없습니다!")
print("반드시 '이 종목을 살 수 있는 USD가 얼마인가?'를 물어야 합니다.")
print()
print("="*80)
print("해결 방법")
print("="*80)
print()
print("우리가 한 것:")
print("  1. TTTS3007R API에 SOXL을 파라미터로 전달")
print("  2. '내가 SOXL을 살 수 있는 USD가 얼마인가?' 질문")
print("  3. API가 계좌의 USD 잔고를 반환 ($339.77)")
print()
print("왜 SOXL을 선택했나?")
print("  - 우리 시스템이 SOXL 전용이라 SOXL로 고정")
print("  - 아무 종목이나 넣어도 같은 USD 잔고가 나옴")
print("    (USD는 계좌에 있고, 종목은 상장 여부만 확인)")
print()
print("="*80)
